// <auto-generated />
namespace MovieStore.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updatingcustomermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatingcustomermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202008061225246_Updating-customer-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
